name: ai-maze-lab
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy
      - pygame
      - matplotlib
      - gymnasium
      - stable-baselines3
      - sb3-contrib
      - torch
